import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='min-h-screen bg-slate-900 text-white relative overflow-x-hidden'>
          {/* Background pattern or gradient can be added here */}
          <div className='absolute inset-0 bg-gradient-to-br from-slate-900 via-slate-900 to-slate-800' />

          {/* Content */}
          <div className='relative z-10'>{children}</div>
        </div>
      </body>
    </html>
  );
}
